swagger: '2.0'
info:
  version: 1.0.0
  title: E-commerce API
  description: API for an e-commerce system
host: 127.0.0.1:5000
schemes:
  - http

paths:

  /login:
    post:
      summary: Log in
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          headers: 
            Set-Cookie:
              type: string

          description: Logged in successfully

        401:
          description: Unauthorized. Invalid credentials

  /logout:
    post:
      summary: Log out
      responses:
        200:
          description: Logout successfully
        401:
          description: Unauthorized. Invalid credentials
  
  /api/books:
    get:
      summary: Get a list of books
      responses:
        200:
          description: Returns a list of books
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
        404:
          description: Not Found. No books available.

  /api/books/{book_id}:
    get:
      summary: Get book details by ID
      parameters:
        - name: book_id
          in: path
          type: integer
          required: true
          description: Book ID to retrieve details
      responses:
        200:
          description: Returns book details
          schema:
            $ref: '#/definitions/Book'
        404:
          description: Not Found. Book not available.

  /api/books/search:
    get:
      summary: Search for books
      parameters:
        - name: q
          in: query
          type: string
          required: true
          description: Search query
      responses:
        200:
          description: Returns a list of books matching the search query
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
        404:
          description: Not Found. No books found for the search query.

  /api/books/add:
    post:
      summary: Add a new book
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        201:
          description: Book added successfully
        400:
          description: Failed to add the book

  /api/books/update/{book_id}:
    put:
      summary: Update a book by ID
      parameters:
        - name: book_id
          in: path
          type: integer
          required: true
          description: Book ID to update
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        200:
          description: Book updated successfully
        404:
          description: Not Found. Book not available
        400:
          description: Failed to update the book

  /api/books/delete/{book_id}:
    delete:
      summary: Delete a book by ID
      parameters:
        - name: book_id
          in: path
          type: integer
          required: true
          description: Book ID to delete
      responses:
        200:
          description: Book deleted successfully
        404:
          description: Not Found. Book not available

  /api/cart/add/{book_id}:
    post:
      summary: Add item to the cart
      parameters:
        - name: book_id
          in: path
          type: integer
          required: true
          description: Book ID to add to the cart
      responses:
        200:
          description: Item added to the cart successfully
        400:
          description: Failed to add item to the cart

  /api/cart/remove/{item_id}:
    delete:
      summary: Remove item from the cart
      parameters:
        - name: item_id
          in: path
          type: integer
          required: true
          description: Cart item ID to remove from the cart
      responses:
        200:
          description: Item removed from the cart successfully
        400:
          description: Failed to remove item from the cart

  /api/cart:
    get:
      summary: View the user's cart
      responses:
        200:
          description: Returns the user's cart contents
          schema:
            type: array
            items:
              $ref: '#/definitions/CartItem'
        401:
          description: Unauthorized. User not logged in

  /api/cart/checkout:
    post:
      summary: Checkout and clear the cart
      responses:
        200:
          description: Checkout successful. Cart has been cleared.
        401:
          description: Unauthorized. User not logged in

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      password:
        type: string
      cart:
        type: array
        items:
          $ref: '#/definitions/CartItem'

  Book:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      description:
        type: string

  CartItem:
    type: object
    properties:
      id:
        type: integer
      user_id:
        type: integer
      book_id:
        type: integer